FROM java:8
MAINTAINER stephan.goertz@gmail.com
EXPOSE 4567
ADD target/hello-docker-java-with-database-sample-1.0-SNAPSHOT.jar /data/hello-docker-java-with-database-sample.jar
CMD java -jar /data/hello-docker-java-with-database-sample.jar
