elasticsearch:
  image: "elasticsearch:2.1.1"
  name: elasticsearch
kibana:
  image: "kibana:4.3.1"
  name: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
cadvisor:
  image: "google/cadvisor:0.19.3"
  name: cadvisor
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  ports:
    - "8080:8080"
  links:
    - elasticsearch
  command: -storage_driver=elasticsearch -storage_driver_es_host=elasticsearch:9200 -alsologtostderr=true
