influxdb:
  image: "tutum/influxdb:0.9"
  name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor
cadvisor:
  image: "google/cadvisor:0.19.3"
  name: cadvisor
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  ports:
    - "8080:8080"
  links:
    - influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
grafana:
  image: "grafana/grafana:2.6.0"
  name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
